name: Docker Test Image

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: ["test/actions"]

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .
          sparse-checkout: |
            01-LandingPage
      - name: folder path
        run: |
          pwd
          ls
          cd 01-LandingPage
          pwd
          ls
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./01-LandingPage
          file: ./backend.Dockerfile
          push: true
          tags: cdq73700/docker-test-actions:latest
